config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tasks/index'
  root to: "tasks#index"

  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end

  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  code        :string
#  description :text
#  due_date    :date             not null
#  name        :string
#  status      :string
#  transitions :string           default([]), is an Array
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  owner_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_category_id  (category_id)
#  index_tasks_on_owner_id     (owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (owner_id => users.id)
#
class Task < ApplicationRecord
  include AASM

  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant', dependent: :destroy
  has_many :participants, through: :participating_users, source: :user
  has_many :notes

  validates :participating_users, presence: true

  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validate :due_date_validity

  accepts_nested_attributes_for :participating_users, reject_if: proc { |attr| attr['user_id'].blank? }, allow_destroy: true
  #reject_if: :all_blank
  #reject_if: proc { |attr| attr['address'].blank? } <--- Esto se pone si tenemos una validacion de presence en participating_users

  before_create :create_code
  after_create :send_email

  enum role: [:responsible, :collaborator ]

  aasm column: 'status' do
    state :pending, initial: true
    state :in_process, :finished

    after_all_transitions :audit_status_change

    event :start do
      transitions from: :pending, to: :in_process
    end

    event :finish do
      transitions from: :in_process, to: :finished
    end
  end

  def audit_status_change
    self.transitions = self.transitions.push(
      {
        from_state: aasm.from_state,
        to_state: aasm.to_state,
        current_event: aasm.current_event,
        timestamp: Time.zone.now
      }
    )
  end

  def due_date_validity
    return if due_date.blank? #El campo es obligatorio desde la migracion,
     #pero este ees un ejemplo de como seria
    return if due_date > Date.today
    errors.add :due_date, 'Invalid due date'

  end

  def create_code
    self.code = "#{owner_id}#{Time.now.to_i.to_s(36)}#{SecureRandom.hex(8)}"
  end

  def send_email
    Tasks::SendEmailJob.perform_in 15, self.id.to_s
  end

end

app/controllers/tasks/notes_controller.rb
class Tasks::NotesController < ApplicationController
  before_action :set_task
  def create
    @note = @task.notes.new(note_params)
    @note.user = current_user
    if @note.save
      redirect_to task_url(@task), notice: "Nota agregada"
    end
  end

  private

  def note_params
    params.require(:note).permit(:body)    
  end

  def set_task
    @task = Task.find(params[:task_id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource #gema cancancan, revisar ability
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    # @tasks = Task.all
    @tasks = Task.joins(:participants).where(
      'owner_id = ? OR participants.user_id = ?',
      current_user.id,
      current_user.id
      ).group(:id) #el group es para que no se repitan tareas
  end

  def show
    @note = Note.new
  end

  def new
    @task = Task.new
    #@task.participating_users.build
  end

  def create
    @task = Task.new(task_params)
    @task.owner = current_user
    if @task.save
      redirect_to task_url(@task), notice: "Tarea creada"
    else
      # @task.participating_users.build
      render :new
    end
  end

  def edit
    @task.participating_users.build
  end

  def update
    if @task.update(task_params)
      redirect_to task_url(@task), notice: "Tarea editada"
    else
      redirect_to tasks_url
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
  end

  private
  def set_task
      @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :category_id, :owner_id, :due_date, participating_users_attributes: [:id, :user_id, :role, :_destroy])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for task do |t| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(task.errors.count, "error") %> prohibited thid task from beging saved: </h2>

    <ul>
        <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    </div>
  <% end %>

  
  <div>
    <%= t.label :name, "Nombre" %>
    <%= t.text_field :name %>
  </div>
  <div>
    <%= t.label :descrption, "Descripción" %>
    <%= t.text_area :description, rows: 20 %>
  </div>
  <div>
    <%= t.label :due_date, "Fecha de entrega"%>
    <%= t.date_field :due_date %>
  </div>
  
  <div>
    <%= t.label :categoria, "Categoría"%>
    <%= t.select :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
  </div>
  
  <div>
    <div class="form-group">
      <%= t.fields_for :participating_users do |participant| %>
          <%= render 'participating_user_fields', f: participant %>
      <% end %>
      <br>
      <br>
      <%= link_to_add_association 'Añadir Participante', t, :participating_users %>
    </div>
  </div>
  <%= t.submit %>
<% end %>

app/views/tasks/_participating_user_fields.html.erb
<div class="nested-fields">
  <div class="field">
      <%= f.label :participating_users %>
      <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :email), :include_blank => true %>
  </div>
  <%= link_to_remove_association "Borrar", f %>


</div>

app/views/tasks/edit.html.erb
<div class="my-5">
  <h1>Editar Tarea</h1>

  <%= render 'form', task: @task %>

</div>

app/views/tasks/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Due_Date</th>
      <th scope="col">Category</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each_with_index do |task, index| %>
      <tr>
        <td><%= index + 1%></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><small><em><%= task.due_date %></small></em></td>
        <td><%= task.category.name %></td>
        <td><%= link_to 'Ver', task_path(task)%></td>
        <td><%= link_to 'Editar', edit_task_path(task) %></td>
        <td><%= link_to 'Eliminar', task_path(task), method: :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nueva Tarea', new_task_path %>

app/views/tasks/new.html.erb
<div class="my-5">
  <h1>Nueva Tarea</h1>

  <%= render 'form', task: @task %>

</div>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-md-6 ">
    <div class="card" style="width: 32rem;">
      <div class="card-body">
        <h5 class="card-title"><%= "Tarea # #{@task.id}"%></h5>
        <p class="card-text"><%= @task.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @task.category.name %></li>
        <li class="list-group-item"><p><small><i><%= @task.due_date %></i></small></p></li>
        <li class="list-group-item"><p><small><%= @task.owner.email %></small></p></li>
      </ul>
      <div class="card-body">
        <a><%= link_to 'Editar Tarea', edit_task_path(@task), class: 'btn btn-primary my-3' %></a>
      </div>
    </div>
  </div>

  <div class="col-md-3 ">
    <div class="notes-container">
      <div class="notes">
        <% @task.notes.each do |note|%>
          <%= render 'tasks/notes/note.html.erb', note: note %>
        <% end %>
      </div>
      <%= form_for @note, url: task_notes_path(task_id: @task.id), remote: true do |f| %>
      <div>
        <%= f.label :body, "Nota" %>
        <%= f.text_area :body, rows: 2 %>
      </div>
        <%= f.submit"Añadir nota", data: {confirm: "Seguro?"}%>
      <% end %>
    </div>
  </div>
</div>