config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tasks/index'
  root to: "tasks#index"

  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end

  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">
      <%= image_tag 'logo.png', class: 'd-inline-block align-top', width: 85 %></a>
    <button aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNavDropdown" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown"></div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Inicio</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="<%= categories_path %>">Categorías</a>
        </li>
      
        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to ' Ingresar', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <%= link_to 'Crear Tarea', new_task_path, class: 'btn btn-light ml-2' %>
      <a><div aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" id="userMenu">
        <% if user_signed_in?%>
          <%= image_tag "https://robohash.org/#{current_user.email}?size=38x38" %>
        <% else%>
          <%= image_tag "https://robohash.org/invitado?size=38x38" %>
        <%end%> 
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>